<?php
/**
 * @file
 * Vision6 main module, which required by other sub modules.
 */

define('VISION6_DEFAULT_ENDPOINT', 'http://www.vision6.com.au/api/jsonrpcserver.php?version=3.0');

/**
 * Implements hook_libraries_info().
 */
function vision6_libraries_info() {
  $libraries['JsonRPC'] = [
    'name' => 'JsonRPC',
    'vendor url' => 'https://github.com/matasarei/JsonRPC',
    'download url' => 'https://github.com/matasarei/JsonRPC/archive/master.zip',
    'version' => 'master',
    'files' => [
      'php' => ['src/JsonRPC/Client.php'],
    ],
  ];

  return $libraries;
}

/**
 * Implements hook_menu().
 */
function vision6_menu() {
  $items['admin/config/development/vision6'] = [
    'title' => 'Vision6 sandbox',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['vision6_sandbox'],
    'access callback' => 'user_access',
    'access arguments' => ['manage vision6 settings'],
  ];

  $items['admin/config/system/vision6'] = [
    'title' => 'Vision6 settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['vision6_settings'],
    'access callback' => 'user_access',
    'access arguments' => ['manage vision6 settings'],
  ];

  $items['admin/config/content/vision6'] = [
    'title' => 'Vision6 Content Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['vision6_content_settings'],
    'access callback' => 'user_access',
    'access arguments' => ['manage vision6 settings'],
  ];

  return $items;
}

/**
 * Form callback for Vision6 settings.
 */
function vision6_settings($form, &$form_state) {
  $form['vision6_option'] = [
    '#type' => 'fieldset',
    '#title' => t('Vision 6 API Settings'),
    '#access' => user_access('manage vision6 settings'),
    '#collapsible' => TRUE,
    '#collapsed' => variable_get('vision6_api_key') != '' && variable_get('vision6_endpoint', '') != '',
  ];

  $form['vision6_option']['vision6_api_key'] = [
    '#type' => 'textfield',
    '#title' => t('Vision6 API key'),
    '#description' => t('Get your API key <a href="http://developers.vision6.com.au/guide/getting-started">here</a>'),
    '#default_value' => variable_get('vision6_api_key'),
  ];

  $form['vision6_option']['vision6_endpoint'] = [
    '#type' => 'textfield',
    '#title' => t('API Endpoint'),
    '#default_value' => variable_get('vision6_endpoint', 'http://www.vision6.com.au/api/jsonrpcserver.php?version=3.0'),
  ];

  $form['vision6_bundles'] = [
    '#type' => 'fieldset',
    '#title' => t('Vision 6 Content Types'),
    '#access' => user_access('manage vision6 settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  ];

  // Add a checkbox that requires them to say "I do", but don't show it,
  // (#access == FALSE) unless they're deleting.
  $visible = FALSE;
  if (!empty($form_state['delete_instances'])) {
    $type_plural = format_plural(count($form_state['delete_instances']), 'type', 'types');
    $affirmation = t('I understand that all field data will be permanently removed from the Content Type @type_plural %node_types.',
      [
        '@type_plural' => $type_plural,
        '%node_types' => implode(', ', $form_state['delete_instances']),
      ]
    );
    $visible = TRUE;
  }

  $node_types = node_type_get_types();

  foreach ($node_types as $node_type) {
    $form['vision6_bundles'][$node_type->type] = [
      '#type' => 'checkbox',
      '#title' => $node_type->name,
      '#description' => t('Add vision 6 to %nodetype nodes', ['%nodetype' => $node_type->name]),
      '#default_value' => variable_get('vision6_' . $node_type->type, FALSE),
    ];
  }

  $form['error'] = [
    '#type' => 'fieldset',
    '#title' => t('Confirm deleting your field'),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
    '#access' => $visible,
    '#weight' => -40,
  ];

  $form['error']['confirmation'] = [
    '#type' => 'checkbox',
    '#title' => !empty($affirmation) ? $affirmation : '',
    '#default_value' => FALSE,
    '#access' => FALSE,
  ];

  $form['submit'] = [
    '#type' => 'submit',
    '#value' => t('Submit'),
  ];

  // If they're deleting, show the confirmation checkbox.
  if (!empty($form_state['delete_instances'])) {
    $form['error']['confirmation']['#access'] = TRUE;
    drupal_set_message(t('You must click the confirmation checkbox to confirm that you want to delete the Vision 6 Syndication options on each node.'), 'warning');
    $form_state['set_var'] = FALSE;
  }

  return $form;
}

/**
 * Validate callback for Vision6 settings form.
 */
function vision6_settings_validate($form, &$form_state) {
  if (!empty($form_state['delete_instances']) && empty($form_state['values']['confirmation'])) {
    form_set_error('error', t('Please check the "I understand" checkbox to indicate you understand that all shipping options data in these fields will be deleted: %fields.', ['%fields' => implode(', ', $form_state['delete_instances'])]));
  }
  else {
    $form_state['set_var'] = TRUE;
  }
}

/**
 * Submit callback for Vision6 settings from.
 */
function vision6_settings_submit($form, &$form_state) {
  variable_set('vision6_api_key', $form_state['values']['vision6_api_key']);
  variable_set('vision6_endpoint', $form_state['values']['vision6_endpoint']);

  $node_types = node_type_get_types();

  // Create the delete array.
  $form_state['delete_instances'] = [];

  foreach ($node_types as $node_type) {
    $enable = !empty($form_state['values'][$node_type->type]) ? $form_state['values'][$node_type->type] : '';
    // Set the Published as syndication options.
    $default = FALSE;
    $field_name = 'field_vis6_published_as_synd';
    $label = 'Publish this content as syndication';
    _vision6_create_fields($node_type->type, $field_name, $label, [], $default, '', $enable, $form_state, 'list_boolean', FALSE);

    // Set the Syndication type.
    $default = 'email';
    $field_name = 'field_vis6_syndication_type';
    $label = 'How do you want to send the syndication';
    $options = vision6_get_syndication_types();
    _vision6_create_fields($node_type->type, $field_name, $label, $options, $default, '', $enable, $form_state);

    // Set the Email type.
    $default = 'html';
    $field_name = 'field_vis6_email_type';
    $label = 'Type of email to send';
    $options = vision6_get_email_types();
    _vision6_create_fields($node_type->type, $field_name, $label, $options, $default, '', $enable, $form_state);

    // Set the include body to syndication options.
    $default = FALSE;
    $field_name = 'field_vis6_inc_body_synd';
    $label = 'Show page content';
    _vision6_create_fields($node_type->type, $field_name, $label, [], $default, '', $enable, $form_state, 'list_boolean', FALSE);

    // Set the Contact Type.
    $default = NULL;
    $field_name = 'field_vis6_type';
    $label = 'Who to contact';
    $options = vision6_get_type();
    _vision6_create_fields($node_type->type, $field_name, $label, $options, $default, '', $enable, $form_state);

    // Set the Contact List.
    $field_name = 'field_vis6_contact_list_id';
    $label = 'Which contact list to send it to?';
    _vision6_create_fields($node_type->type, $field_name, $label, '_vision6_get_contact_list_id', $default, '', $enable, $form_state);
    if ($form_state['set_var']) {
      variable_set('vision6_' . $node_type->type, $enable);
    };

    // Set the Contact List.
    $default = FALSE;
    $field_name = 'field_vis6_previous_message_id';
    $label = 'Previous Message ID';
    _vision6_create_fields($node_type->type, $field_name, $label, $default, $default, '', $enable, $form_state, 'text');
    if ($form_state['set_var']) {
      variable_set('vision6_' . $node_type->type, $enable);
    };
  }
}

/**
 * Form callback for Vision6 settings page.
 */
function vision6_content_settings($form, &$form_state) {
  $form['vision6_content'] = [
    '#access' => user_access('access vision6 publish'),
    '#type' => 'fieldset',
    '#title' => t('Content Settings'),
    '#access' => user_access('access vision6 publish'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  ];

  $form['vision6_content']['vision6_title_style'] = [
    '#type' => 'textfield',
    '#title' => t('Vision6 Email Title Style'),
    '#description' => t('This must be valid css to be placed in the style attribute wrapped around the Title of the article within the email. Leave this blank if you do not know how to use this field.'),
    '#default_value' => variable_get('vision6_title_style', ''),
  ];

  $header = variable_get('vision6_header');
  $form['vision6_content']['vision6_header'] = [
    '#type' => 'text_format',
    '#title' => t('Vision6 Email Header'),
    '#description' => t('The header text will appear at the top of Vision6 emails'),
    '#default_value' => $header['value'],
    '#rows' => 10,
    '#format' => empty($header['format']) ? 'full_html' : $header['format'],
  ];

  $footer = variable_get('vision6_footer');
  $form['vision6_content']['vision6_footer'] = [
    '#type' => 'text_format',
    '#title' => t('Vision6 Email Footer'),
    '#description' => t('The header text will appear at the top of Vision6 emails'),
    '#default_value' => $footer['value'],
    '#rows' => 10,
    '#format' => empty($footer['format']) ? 'full_html' : $footer['format'],
  ];

  return system_settings_form($form);
}

/**
 * Form callback for the API testing page.
 */
function vision6_sandbox($form, &$form_state) {
  $form['addMessage'] = [
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#tree' => TRUE,
    '#title' => 'addMessage call',
    '#description' => l(t('addMessage API documentation'), 'http://developers.vision6.com.au/3.0/method/addmessage'),
  ];

  $form['addMessage']['api_key'] = [
    '#type' => 'value',
    '#value' => variable_get('vision6_api_key'),
  ];

  // @todo: Consider adding SMS to the type.
  $form['addMessage']['type'] = [
    '#type' => 'value',
    '#value' => 'email',
  ];

  $form['addMessage']['name'] = [
    '#type' => 'textfield',
    '#title' => 'Name',
  ];

  $form['addMessage']['subject'] = [
    '#type' => 'textfield',
    '#title' => 'Subject',
  ];

  // @todo: Need to review the differences between these, not clear in
  // documentation.
  $form['addMessage']['email_type'] = [
    '#type' => 'select',
    '#title' => 'Email Type',
    '#options' => [
      'html' => t('HTML'),
      'raw_html' => t('Raw HTML'),
    ],
  ];

  $form['addMessage']['html_content'] = [
    '#type' => 'textarea',
    '#title' => 'HTML Content',
  ];

  $form['addMessage']['actions'] = [
    '#type' => 'container',
  ];

  $form['addMessage']['actions']['submit'] = [
    '#type' => 'submit',
    '#value' => 'addMessage()',
    '#submit' => ['vision6_sandbox_add_message_submit'],
  ];

  $form['addBatch'] = [
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#tree' => TRUE,
    '#title' => 'addBatch call',
    '#description' => l(t('addBatch API documentation'), 'http://developers.vision6.com.au/3.0/method/addbatch'),
  ];

  $form['addBatch']['api_key'] = [
    '#type' => 'value',
    '#value' => variable_get('vision6_api_key'),
  ];

  $form['addBatch']['message_id'] = [
    '#type' => 'textfield',
    '#title' => 'Message ID',
  ];

  $form['addBatch']['is_test'] = [
    '#type' => 'value',
    '#value' => TRUE,
  ];

  $form['addBatch']['contact_populations'] = [
    '#type' => 'fieldset',
    '#title' => 'Contacts',
    '#tree' => TRUE,
    0 => [
      '#tree' => TRUE,
    ],
  ];

  $form['addBatch']['contact_populations'][0]['type'] = [
    '#type' => 'select',
    '#title' => 'Type',
    '#options' => [
      'contacts' => t('Contacts'),
      'list' => t('List'),
      'unsent' => t('Unsent'),
    ],
  ];

  $form['addBatch']['contact_populations'][0]['list_id'] = [
    '#type' => 'textfield',
    '#title' => 'List ID',
    '#default_value' => 440550,
  ];

  $form['addBatch']['actions'] = [
    '#type' => 'container',
  ];

  $form['addBatch']['actions']['submit'] = [
    '#type' => 'submit',
    '#value' => 'addBatch()',
    '#submit' => ['vision6_sandbox_add_batch_submit'],
  ];

  return $form;
}

/**
 * Submit handler for the addMessage function tester.
 */
function vision6_sandbox_add_message_submit(&$form, &$form_submit) {
  try {
    $client = _vision6_get_api_client();
  }
  catch (Exception $e) {
    watchdog('vision6', 'Unable to retrieve an API client, is the JsonRPC library installed correctly?', [], WATCHDOG_CRITICAL);
    drupal_set_message(t('Unable to retrieve an API client, is the JsonRPC library installed correctly?'), 'error');
  }

  $values = &$form_submit['values']['addMessage'];
  unset($values['actions']);

  $api_key = variable_get('vision6_api_key');
  try {
    $message_id = $client->addMessage($api_key, $values);
  }
  catch (Exception $e) {
    watchdog_exception('vision6', $e);
    drupal_set_message(t('Unable to add message to the Vision6 client'), 'error');
  }

  drupal_set_message(t('Please enable the Devel module to properly use this function. NOTE: Do not leave the Devel module enabled in Production'));
  drupal_set_message(t('Message ID: %message', ['%message' => $message_id]));
}

/**
 * Submit handler for the addBatch function tester.
 */
function vision6_sandbox_add_batch_submit(&$form, &$form_submit) {
  try {
    $client = _vision6_get_api_client();
  }
  catch (Exception $e) {
    watchdog_exception('vision6', $e);
    drupal_set_message(t('Could not initiate Vision6 API due to the following error: &nbsp;') . check_plain($e->getMessage()), 'error');
  }

  $values = &$form_submit['values']['addBatch'];
  unset($values['actions']);
  $api_key = variable_get('vision6_api_key');
  $batch_id = $client->addBatch($api_key, $values['message_id'], $values['contact_populations']);
  drupal_set_message(t('Please enable the Devel module to properly use this function. NOTE: Do not leave the Devel module enabled in Production'));
  drupal_set_message(t('Batch ID: %batch', ['%batch' => $batch_id]));
}

/**
 * Helper function to construct an API instance.
 *
 * @return \JsonRPC\Client
 *   Returns a JSON RPC client for usage with the Vision6 API. May return NULL
 *   if there was an error loading required libraries.
 *
 * @throws Exception
 */
function _vision6_get_api_client() {
  $loaded = libraries_load('JsonRPC');
  if (!$loaded['installed'] || !$loaded['loaded']) {
    throw new Exception('Unable to load JsonRPC library');
  }

  $endpoint = variable_get('vision6_endpoint', VISION6_DEFAULT_ENDPOINT);

  return new \JsonRPC\Client($endpoint);
}

/**
 * Implements hook_permission().
 */
function vision6_permission() {
  return [
    'access vision6 publish' => [
      'title' => t('Publish as Syndication'),
      'description' => t('Publish content to Vision6 system'),
    ],
    'manage vision6 settings' => [
      'title' => t('Manage Vision 6 API Settings'),
      'description' => t('Change the API key and endpoint for Vision 6'),
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function vision6_form_node_form_alter(&$form, &$form_state, $form_id) {
  if (!variable_get('vision6_' . $form['type']['#value'], FALSE)) {
    return;
  }

  $form['#validate'][] = '_vision6_form_node_form_validate';

  // The js sets the values of my newly created fields back to the original,
  // drupal fields. The new fields are in the vertical tab to meet the func
  // spec.
  drupal_add_js(drupal_get_path('module', 'vision6') . '/js/vision6.js', 'file');

  // Get rid of the node fields and move them to a fieldset.
  $field_vis6_published_as_synd = $form['field_vis6_published_as_synd'];
  $field_vis6_syndication_type = $form['field_vis6_syndication_type'];
  $field_vis6_email_type = $form['field_vis6_email_type'];
  $field_vis6_type = $form['field_vis6_type'];
  $field_vis6_contact_list_id = $form['field_vis6_contact_list_id'];
  $field_vis6_inc_body_synd = $form['field_vis6_inc_body_synd'];
  $form['field_vis6_previous_message_id']['#access'] = FALSE;

  $form['options']['field_vis6_new_published_as_synd'] = $field_vis6_published_as_synd;

  $form['options']['syndication'] = [
    '#access' => user_access('access vision6 publish'),
    '#type' => 'fieldset',
    '#title' => t('Syndication options'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#weight' => 100,
    '#states' => [
      'visible' => [
        ':input[name="field_vis6_new_published_as_synd[und]"]' => [
          'checked' => TRUE,
        ],
      ],
    ],
  ];

  $form['options']['syndication']['field_vis6_new_syndication_type'] = $field_vis6_syndication_type;

  $form['options']['syndication']['field_vis6_new_email_type'] = $field_vis6_email_type;

  $form['options']['syndication']['contact_populations'] = [
    '#type' => 'fieldset',
    '#title' => 'Contacts',
    '#weight' => 110,
  ];

  $form['options']['syndication']['field_vis6_new_inc_body_synd'] = $field_vis6_inc_body_synd;

  $form['options']['syndication']['contact_populations']['field_vis6_new_type'] = $field_vis6_type;

  $form['options']['syndication']['contact_populations']['field_vis6_new_contact_list_id'] = $field_vis6_contact_list_id;

  $form['field_vis6_published_as_synd']['#attributes']['style'] = 'display:none;';
  $form['field_vis6_syndication_type']['#attributes']['style'] = 'display:none;';
  $form['field_vis6_email_type']['#attributes']['style'] = 'display:none;';
  $form['field_vis6_type']['#attributes']['style'] = 'display:none;';
  $form['field_vis6_contact_list_id']['#attributes']['style'] = 'display:none;';
  $form['field_vis6_inc_body_synd']['#attributes']['style'] = 'display:none;';
}

/**
 * Form validate handler.
 *
 * A custom validation function to ensure that if the user selects a page node
 * to be syndicated, that the other syndication fields are filled in.
 */
function _vision6_form_node_form_validate(&$form, &$form_state) {
  // If this should be syndicated, then make the other fields mandatory.
  // @todo: Consider adding compulsory param to the node form instead of this.
  if ($form_state['values']['field_vis6_new_published_as_synd'][LANGUAGE_NONE][0]['value']) {
    if (!$form_state['values']['field_vis6_new_syndication_type'][LANGUAGE_NONE][0]['value']) {
      form_set_error('field_vis6_new_syndication_type', t('The syndication type is required.'));
    }
    if (!$form_state['values']['field_vis6_new_email_type'][LANGUAGE_NONE][0]['value']) {
      form_set_error('field_vis6_new_email_type', t('The email type is required.'));
    }
    if (!$form_state['values']['field_vis6_new_type'][LANGUAGE_NONE][0]['value']) {
      form_set_error('field_vis6_new_type', t('The contact type is required.'));
    }
    if (!$form_state['values']['field_vis6_new_contact_list_id'][LANGUAGE_NONE][0]['value']) {
      form_set_error('field_vis6_new_contact_list_id', t('The contact list is required.'));
    }
  }
}

/**
 * Implements hook_node_insert().
 */
function vision6_node_insert($node) {
  _vision6_node_beforesave($node);
}

/**
 * Implements hook_node_update().
 */
function vision6_node_update($node) {
  _vision6_node_beforesave($node);
}

/**
 * Helper to update node when the new state is set to published during save.
 *
 * @param object $node
 *   Drupal node object.
 * @param string $previous_state
 *   Previous publishing state of the node moderation status.
 * @param string $new_state
 *   New state of the node moderation status.
 */
function vision6_workbench_moderation_transition($node, $previous_state, $new_state) {
  if ($new_state == 'published') {
    _vision6_node_beforesave($node);
  }
}

/**
 * Custom handler function to add vision6 related data to the node on save.
 *
 * @param object $node
 *   Node object.
 */
function _vision6_node_beforesave($node) {
  global $base_url;

  try {
    $wrapper = entity_metadata_wrapper('node', $node);
  }
  catch (Exception $e) {
    watchdog_exception('vision6', $e);
    drupal_exit();
  }

  if (!variable_get('vision6_' . $node->type, FALSE) || !user_access('access vision6 publish')) {
    return;
  }

  if (module_exists('workbench_moderation') && ($node->workbench_moderation) && $node->workbench_moderation['current']->state != 'published') {
    return;
  }
  elseif (!$wrapper->status->value()) {
    return;
  }

  if (!empty($node->field_vis6_published_as_synd)) {
    if (!$wrapper->field_vis6_published_as_synd->value()) {
      return;
    }
  }
  else {
    return;
  }

  $add_message = [
    'type' => $wrapper->field_vis6_syndication_type->value(),
    'name' => $node->title,
    'email_type' => $wrapper->field_vis6_email_type->value(),
    'subject' => $node->title,
    'html_content' => '<div style="' . variable_get('vision6_title_style', '') . '">' . l($node->title, url('node/' . $node->nid, ['absolute' => TRUE])),
  ];

  if ($add_message['type'] == 'email') {
    $add_message['email_type'] = $wrapper->field_vis6_email_type->value();
  }

  if ($wrapper->field_vis6_inc_body_synd->value()) {
    $body = field_get_items('node', $node, 'body');
    if ($body) {
      $body_node = clone $node;
      while (strpos($body_node->body[LANGUAGE_NONE][0]['value'], '[[nid:')) {
        $embed_nodes = substr($body_node->body[LANGUAGE_NONE][0]['value'], strpos($body_node->body[LANGUAGE_NONE][0]['value'], '<div class="embed">[[nid:'));
        $embed_nodes = substr($embed_nodes, 0, strpos($embed_nodes, '</div') + 6);
        $body_node->body[LANGUAGE_NONE][0]['value'] = str_replace($embed_nodes, ' ', $body_node->body[LANGUAGE_NONE][0]['value']);
      }
      $body_view = field_view_field('node', $body_node, 'body', 'full');
      $body_text = preg_replace("/<img[^>]+\>/i", " ", render($body_view));
      $body_text = preg_replace("/<object[^>]+\>/i", " ", $body_text);
      $body_text = preg_replace("/<iframe[^>]+\>/i", " ", $body_text);
      $body_text = preg_replace("/<video[^>]+\>/i", " ", $body_text);
      $add_message['html_content'] .= '<br/><br/>' . check_markup($body_text, $body[0]['format']);
    }
  }

  $var_header = variable_get('vision6_header');
  if (is_array($var_header)) {
    $var_header = str_replace('src="/sites', 'src="' . $base_url . '/sites', $var_header);
    $add_message['html_content'] = check_markup($var_header['value'], $var_header['format']) . '<br/><br/>' . $add_message['html_content'];
  }

  $var_footer = variable_get('vision6_footer');
  if (is_array($var_footer)) {
    $var_footer = str_replace('src="/sites', 'src="' . $base_url . '/sites', $var_footer);
    $add_message['html_content'] .= '<br/><br/>' . check_markup($var_footer['value'], $var_footer['format']);
  }
  $add_batch = [
    [
      'type' => $wrapper->field_vis6_type->value(),
      'list_id' => $wrapper->field_vis6_contact_list_id->value(),
      'time' => 'now',
    ],
  ];

  try {
    $client = _vision6_get_api_client();
  }
  catch (Exception $e) {
    watchdog_exception('vision6', $e);
    drupal_set_message(t('Could not publish as Syndication due to the following error: &nbsp;') . check_plain($e->getMessage()), 'error');
  }

  $add_message['html_content'] .= '</div>';
  $add_message['html_content'] .= '<table style="width: 100%;"><tr><td align="center" valign="top"><center><table border="0" align="center" style="max-width:714px;"><tbody style="width:100%;"><tr><td>' . $add_message['html_content'];
  $add_message['html_content'] .= '</td></tr></tbody></table></center></td></tr></table>';

  if ($wrapper->field_vis6_type->value() == 'unsent' && $wrapper->field_vis6_previous_message_id->value()) {
    $add_message['id'] = $wrapper->field_vis6_previous_message_id->value();
    unset($add_message['type']);
    $message = variable_get('vision6_api_key');
    try {
      $message_id = $client->editMessage($message, $add_message);
    }
    catch (Exception $e) {
      watchdog_exception('vision6', $e);
      drupal_set_message(t('Could not edit message due to the following error: &nbsp;') . check_plain($e->getMessage()), 'error');
    }
  }
  else {
    $api_key = variable_get('vision6_api_key');
    try {
      $message_id = $client->addMessage($api_key, $add_message);
    }
    catch (Exception $e) {
      watchdog_exception('vision6', $e);
      drupal_set_message(t('Could not add message due to the following error: &nbsp;') . check_plain($e->getMessage()), 'error');
    }
  }

  if ($message_id) {
    $api_key = variable_get('vision6_api_key');
    $batch_id = $client->addBatch($api_key, $message_id, $add_batch);
    if ($batch_id) {
      drupal_set_message(t('Published as Syndication.'), 'status');
      $node->field_vis6_published_as_synd[LANGUAGE_NONE][0]['value'] = 0;
      $node->field_vis6_previous_message_id[LANGUAGE_NONE][0]['value'] = $message_id;
      field_attach_update('node', $node);
    }
  }
}

/**
 * Helper to get the client list ids from Vision 6.
 *
 * @return array
 *   Contact list array keyed by contact ID.
 */
function _vision6_get_contact_list_id() {
  $results = [];
  // Get the client list ids from Vision 6.
  try {
    $client = _vision6_get_api_client();
  }
  catch (Exception $e) {
    watchdog_exception('vision6', $e);
    drupal_set_message(t('Could not publish as Syndication due to the following error: &nbsp;') . check_plain($e->getMessage()), 'error');
  }

  $api_key = variable_get('vision6_api_key');
  try {
    $result = $client->searchLists($api_key, [], 0, 0, 'name', 'ASC');
  }
  catch (Exception $e) {
    watchdog_exception('vision6', $e);
    drupal_set_message(t('We could not find the list name.') . check_plain($e->getMessage()), 'error');
  }

  if (!isset($result['error'])) {
    foreach ($result as $item) {
      $results[$item['id']] = $item['name'];
    }
  }
  else {
    watchdog('vision6', 'Unable to retrieve The client list from Vision 6 due to Error number: %errnum. Error Message: %errmessage', [
      '%errnum' => $result['error']['code'],
      '%errmessage' => $result['error']['message'],
    ], WATCHDOG_ERROR);
    drupal_set_message(t('Unable to retrieve The client list from Vision 6 due to Error number: %errnum. Error Message: %errmessage', [
      '%errnum' => $result['error']['code'],
      '%errmessage' => $result['error']['message'],
    ]), 'error');
  }

  return $results;
}

/**
 * Helper to get the details of a vision6 list by the client id.
 *
 * @return bool|object
 *   Contact list object or FALSE.
 */
function _vision6_get_contact_list_by_id($listid) {
  try {
    $client = _vision6_get_api_client();
  }
  catch (Exception $e) {
    watchdog_exception('vision6', $e);
    drupal_set_message(t('We could not find the list name.') . check_plain($e->getMessage()), 'error');
  }

  try {
    $result = $client->getListById([
      variable_get('vision6_api_key'),
      $listid,
    ]);
  }
  catch (Exception $e) {
    watchdog_exception('vision6', $e);
    drupal_set_message(t('We could not find the list name.') . check_plain($e->getMessage()), 'error');
  }

  if (!isset($result['error'])) {
    return $result;
  }
  else {
    watchdog('vision6', 'Unable to retrieve The client list from Vision 6 due to Error number: %errnum. Error Message: %errmessage', [
      '%errnum' => $result['error']['code'],
      '%errmessage' => $result['error']['message'],
    ], WATCHDOG_ERROR);
    drupal_set_message(t('Unable to retrieve The client list from Vision 6 due to Error number: %errnum. Error Message: %errmessage', [
      '%errnum' => $result['error']['code'],
      '%errmessage' => $result['error']['message'],
    ]), 'error');

    return FALSE;
  }
}

/**
 * Helper to create Vision6 related fields.
 *
 * Take in field details and create them in the bundle requested with the
 * $bundle field.
 *
 * @param string $bundle
 *   The bundle (content type) to add the fields to.
 * @param string $field_name
 *   The machine name for the field.
 * @param string $label
 *   The field label.
 * @param string $options
 *   An array of options for select fields.
 * @param string $default
 *   The field default value.
 * @param string $description
 *   The field description.
 * @param string|bool $enable
 *   A string or boolean to create or delete the field, TRUE = create.
 * @param string $form_state
 *   The form_state array.
 * @param string $field_type
 *   The type of field, the machine name based on the form API.
 * @param bool $multiple
 *   The list type field can be multiple.
 */
function _vision6_create_fields($bundle, $field_name, $label, $options, $default, $description, $enable, &$form_state, $field_type = 'list_text', $multiple = FALSE) {
  $weights = [
    'field_vis6_published_as_synd' => 100,
    'field_vis6_syndication_type' => 101,
    'field_vis6_email_type' => 102,
    'field_vis6_inc_body_synd' => 103,
    'field_vis6_type' => 104,
    'field_vis6_contact_list_id' => 105,
    'field_vis6_previous_message_id' => 106,
  ];
  $resubmit = _vision6_check_field($bundle, $enable, $field_name, $label, $default, $description, $weights[$field_name], $options, $form_state['values']['confirmation'], $field_type, $multiple);

  // If the function returned FALSE, show the please confirm checkbox.
  if (!$resubmit) {
    if (!in_array($bundle, $form_state['delete_instances'])) {
      $form_state['delete_instances'][] = $bundle;
      $form_state['rebuild'] = TRUE;
    }
  }
}

/**
 * Check if a field exists and if it doesn't, create it.
 *
 * @param string $bundle
 *   Bundle.
 * @param string|bool $enable
 *   Flag to indicate if the user wants to enable or disable this field.
 * @param string $field_name
 *   The name of the field to be created.
 * @param string $label
 *   The field label.
 * @param string $default
 *   The default value for the field.
 * @param string $description
 *   The field description.
 * @param string $weight
 *   The field weight.
 * @param string $options
 *   The field options if it has any.
 * @param string $confirmed
 *   If the user has confirmed deleting the field.
 * @param string $field_type
 *   The type of field, defaults to list_text.
 *
 * @return bool
 *   Returns TRUE if the delete option has been approved or FALSE otherwise.
 */
function _vision6_check_field(
  $bundle,
  $enable,
  $field_name,
  $label,
  $default,
  $description,
  $weight,
  $options,
  $confirmed,
  $field_type = 'list_text',
  $multiple = FALSE
) {
  $instance = field_info_instance('node', $field_name, $bundle);
  $currently_enabled = !empty($instance);

  if ($enable && !$currently_enabled) {
    _vision6_create_instance($field_name, $field_type, FALSE, 'node', $bundle, $label, $default, $options, $description, $weight, TRUE, $multiple);

    // Set default field values of every existing node of $bundle bundle to 0.
    _vision6_field_initialise('node', $bundle, $field_name, $default);

    drupal_set_message(t('%label has been enabled on the %type Content Type', [
      '%type' => $bundle,
      '%label' => $label,
    ]));
  }
  elseif (!$enable && $currently_enabled) {
    // Conversely, if they *don't* want it and it's currently enabled,
    // warn them about the consequences or do it.
    // If they haven't clicked the "confirm" checkbox, rebuild and get them,
    // to do it.
    if (empty($confirmed)) {
      return FALSE;
    }
    else {
      // Otherwise they already have clicked it and we can delete.
      field_delete_instance($instance);

      drupal_set_message(t('%label management has been disabled on the %bundle Content Type', [
        '%bundle' => $bundle,
        '%label' => $label,
      ]));
    }
  }

  return TRUE;
}

/**
 * Function _vision6_create_instance.
 *
 * Creates a field and an instance of a commerce_postmaster field on the
 * specified bundle.
 *
 * @param string $field_name
 *   The name of the field; if it already exists, a new instance of the
 *   existing field will be created. For fields governed by the Commerce
 *   modules, this should begin with commerce_.
 * @param string $field_type
 *   The type of field to create.
 * @param bool $required
 *   If this field is a required field.
 * @param string $entity_type
 *   The type of entity the field instance will be attached to..
 * @param string $bundle
 *   The bundle name of the entity the field instance will be attached to.
 * @param string $label
 *   The label of the field instance.
 * @param string $default
 *   The default value for this field.
 * @param array $options
 *   An array of field options for select lists..
 * @param string $description
 *   The field description.
 * @param int $weight
 *   The weight of the field.
 * @param bool $no_display
 *   Hide the field display.
 */
function _vision6_create_instance(
  $field_name,
  $field_type,
  $required,
  $entity_type,
  $bundle,
  $label,
  $default,
  $options = [],
  $description = NULL,
  $weight = 0,
  $no_display = TRUE,
  $multiple = FALSE
) {

  // Look for the field and instance.
  $field = field_info_field($field_name);
  $instance = field_info_instance($entity_type, $field_name, $bundle);

  // If there is no field then create one based on the passed in values.
  if (empty($field)) {
    $field = [
      'field_name' => $field_name,
      'type' => $field_type,
      'cardinality' => 1,
      'translatable' => FALSE,
      'locked' => FALSE,
      'default_value' => [['value' => $default]],
    ];
    // If it shouldn't be displayed hide it.
    if ($no_display) {
      $field['display'] = [
        'default' => [
          'label' => 'above',
          'type' => 'hidden',
        ],
      ];
    }
    // If there are passed in options, create them for the select field.
    if (is_array($options)) {
      if (count($options)) {
        $field['settings'] = [
          'allowed_values' => $options,
          'allowed_values_function' => '',
        ];
        $field['widget'] = [
          'type' => 'select',
        ];
      }
    }
    else {
      $field['settings'] = [
        'allowed_values' => [],
        'allowed_values_function' => $options,
      ];
      $field['widget'] = [
        'type' => 'select',
      ];
    }

    // If the field type is boolean, set the values.
    if ($field_type == 'list_boolean') {
      $field['settings'] = [
        'allowed_values' => [0, 1],
        'allowed_values_function' => '',
      ];
    }
    $field['#multiple'] = $multiple;
    field_create_field($field);
  }

  // If there is no field instance then create one.
  if (empty($instance)) {
    $instance = [
      'field_name' => $field_name,
      'entity_type' => $entity_type,
      'bundle' => $bundle,
      'label' => $label,
      'required' => $required,
      'widget' => [
        'weight' => $weight,
      ],
      'settings' => [],
      'description' => $description,
      'default_value' => [['value' => $default]],
    ];

    // If it shouldn't be displayed hide it.
    if ($no_display) {
      $instance['display'] = [
        'default' => [
          'label' => 'above',
          'type' => 'hidden',
        ],
      ];
    }

    // If it's a boolean st it's allowed values.
    if ($field_type == 'list_boolean') {
      $instance['widget'] = [
        'type' => 'options_onoff',
        'settings' => [
          'display_label' => TRUE,
        ],
      ];
    }

    // Create the field instance.
    field_create_instance($instance);
  }
}

/**
 * Initialize handler.
 *
 * This functions parses all the nodes of the specified bundle, and
 * initialize the required field to the default value.
 *
 * @param string $bundle
 *   The bundle with the node entity.
 * @param string $field_name
 *   The name of the field.
 * @param string $default
 *   The field default value.
 */
function _vision6_field_initialise($bundle, $field_name, $default) {
  // Load every node of $bundle type.
  $nodes = node_load_multiple([], ['type' => $bundle]);
  // Parses each node to initialize its stock value.
  foreach ($nodes as $node) {
    $wrapper = entity_metadata_wrapper('node', $node);
    $wrapper->$field_name = $default;
    $wrapper->save();
  }
}

/**
 * Returns an array of syndication types.
 *
 * @return array
 *    The array used mainly in forms.
 */
function vision6_get_syndication_types() {
  return [
    'email' => t('Email'),
  ];
}

/**
 * Getter of email types.
 *
 * @return array
 *   The array of email types.
 */
function vision6_get_email_types() {
  return [
    'html' => t('HTML'),
  ];
}

/**
 * Getter of syndication types.
 *
 * @return array
 *   The array used mainly in forms.
 */
function vision6_get_type() {
  return [
    'list' => t('Send to all contacts in the List'),
    'unsent' => t('Only send to Contacts who have not been sent the Message'),
  ];
}
